name: RAIN
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      -
        name: run preprocess
        run: |   
          python process.py
      -
        name: Train model
        run: |     
          python train_logisticR.py
          
      - name: Write CML report
      
        run: |
          # Post reports as comments in GitHub PRs
          echo "## Model Metrics" > report.md
          cat metrics>>report.md
          cml send-comment report.md    
         
        
