name: farmers
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      -
        name: run preprocess
        run: |   
          python process.py
      -
        name: Train model
        run: |     
          python train_logisticR.py
          echo "## Model Metrics" > report.md
          cat metrics.json>>report.md
          
          # Add figure to the report
          echo "## Validating results by region" >> report.md
          cml-publish CM_ALL_LR.png --md >> report.md
          cml-send-comment report.md
