name: model-training
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      -
        name: run preprocess
        run: |   
          python process.py           

      - name: Write CML report
      
        run: |   
          cml publish CM_ALL_LR.png --md >> report.md
          cml send-comment report.md
